Repository akbarpn136/pidol, pull requests merged in 2020-10, with the labels that each got.

#1 Coba PR
  .gitignore
  requirements.txt
Labels: perawatan, perdana

#2 Membuat window dan dependency
  main.py
  requirements.txt
Labels: ketergantungan, perawatan, perdana

#3 buat window dengan class based
  main.py
Labels: perawatan

#7 Membuat ui dengan glade
  main.py
  ui.glade
Labels: perawatan

#8 Letakin Toolbar
  asset/floppy.png
  main.py
Labels: perawatan

#9 Buat dialog yang disesuaikan
  main.py
Labels: perawatan

#11 Kelola character
  Controllers/CharacterController.cs
  Models/Character.cs
  Models/RpgClass.cs
  Properties/launchSettings.json
Labels: perawatan

#12 Terapin dependency injection kedalam aplikasi
  Controllers/CharacterController.cs
  Models/ServiceResponse.cs
  Services/CharacterService/CharacterService.cs
  Services/CharacterService/ICharacterService.cs
  Startup.cs
Labels: perawatan

#13 Menggunakan AutoMapper sebagai Dependency Injection
  AutoMapperProfile.cs
  Services/CharacterService/CharacterService.cs
  Startup.cs
Labels: perawatan

#14 Tambah fungsi update
  Controllers/CharacterController.cs
  Dtos/Character/UpdateCharacterDto.cs
  Services/CharacterService/CharacterService.cs
  Services/CharacterService/ICharacterService.cs
Labels: perawatan

#15 Tambah funsional hapus bagian character
  Controllers/CharacterController.cs
  Services/CharacterService/CharacterService.cs
  Services/CharacterService/ICharacterService.cs
Labels: perawatan

#16 Update merge project
  README.md
  pidol.csproj
Labels: perdana

#17 Buat migrasi koneksi serta kelola Db
  Data/DataContext.cs
  Migrations/20201025000833_InitialCreate.Designer.cs
  Migrations/20201025000833_InitialCreate.cs
  Migrations/DataContextModelSnapshot.cs
  Startup.cs
  appsettings.Development.json
  pidol.csproj
Labels: perawatan

#18 kelola service untuk character
  AutoMapperProfile.cs
  Services/CharacterService/CharacterService.cs
Labels: perawatan
